os:
  - linux
  - osx
language: generic
sudo: required
dist: bionic
osx_image: xcode11
env: SWIFT_VERSION=5.1
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
script:
  - swift package reset
  - swift build
  - swift test --enable-code-coverage
after_success:
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    bash <(curl -s https://codecov.io/bash);
  fi